LOCAL:
    temp-directory: /output/tmp
    dropseq-wrapper: /usr/local/drop-seq-tools/drop-seq-tools-wrapper.sh
    memory: 20g
META:
    species:
        - HUMAN
        - MOUSE
    ratio: 0.2
    reference-file: reference.fasta
    annotation-file: annotation.gtf
    reference-directory: /meta/
FILTER:
    5-prime-smart-adapter: CACACTCTTTCCCTACACGACGC
    cell-barcode:
        start: 1
        end:   12
        min-quality: 30
        num-below-quality: 0
    UMI-barcode:
        start: 13
        end: 20
        min-quality: 30
        num-below-quality: 0
    trimmomatic:
        adapters-file: NexteraPE-PE.fa
        LEADING: 3
        TRAILING: 3
        SLIDINGWINDOW:
            windowSize: 4
            requiredQuality: 20
        MINLEN: 20
        ILLUMINACLIP:
            seedMismatches: 2
            palindromeClipThreshold: 30
            simpleClipThreshold: 10
MAPPING:
    STAR:
        outFilterMismatchNmax: 10
        outFilterMismatchNoverLmax: 0.3
        outFilterMismatchNoverReadLmax: 1
        outFilterMatchNmin: 0
        outFilterMatchNminOverLread: 0.66
        outFilterScoreMinOverLread: 0.66
EXTRACTION:
    UMI-edit-distance: 0
    minimum-counts-per-UMI: 1
